import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import type {
  ActionArtifact,
  FollowUpTask,
  InterventionQueueItem,
  MediaryLoopOutput,
} from "@/src/types/mediary";

const DEFAULT_OUTPUT_DIR = path.join(os.homedir(), ".hermes", "deliverables");

function ensureDir(dirPath: string): void {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
  }
}

function sanitizeFilename(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function findQueueItem(
  queue: InterventionQueueItem[],
  employeeId: string,
): InterventionQueueItem | undefined {
  return queue.find((q) => q.employeeId === employeeId);
}

// ── HR Ops case ──────────────────────────────────────────────────────────────

function formatHrOpsCase(
  artifact: ActionArtifact,
  queueItem: InterventionQueueItem | undefined,
): string {
  const riskScore = queueItem?.riskScore ?? "N/A";
  const riskBucket = queueItem?.riskBucket ?? "N/A";
  const route = queueItem?.route ?? "Sustained High: HR Ops queue";
  const rationale = queueItem?.decisionRationale ?? artifact.body;
  const nextStep = queueItem?.nextStep ?? "";
  const followUpCadence = queueItem?.followUpCadence ?? "48-hour HR Ops review cycle";
  const team = queueItem?.team ?? "Unknown";

  return [
    `# ${artifact.title}`,
    "",
    `**Employee:** ${artifact.employeeName}`,
    `**Team:** ${team}`,
    `**Owner:** ${artifact.owner}`,
    `**Risk Score:** ${riskScore} (${riskBucket})`,
    `**Route:** ${route}`,
    "",
    "---",
    "",
    "## Trend & Rationale",
    "",
    rationale,
    "",
    "## Next Steps",
    "",
    nextStep
      ? `1. ${nextStep}`
      : "1. Review case packet with HR Ops lead.",
    "2. Confirm alignment with direct manager.",
    "3. Validate focus-block execution and workload redistribution.",
    "",
    "## Follow-Up Cadence",
    "",
    followUpCadence,
    "",
    "---",
    "",
    `*Generated by Mediary — ${new Date().toISOString().split("T")[0]}*`,
    "",
  ].join("\n");
}

// ── Manager brief ────────────────────────────────────────────────────────────

function formatManagerBrief(
  artifact: ActionArtifact,
  queueItem: InterventionQueueItem | undefined,
): string {
  const riskScore = queueItem?.riskScore ?? "N/A";
  const riskBucket = queueItem?.riskBucket ?? "N/A";
  const rationale = queueItem?.decisionRationale ?? artifact.body;
  const followUpCadence = queueItem?.followUpCadence ?? "3 working days";
  const team = queueItem?.team ?? "Unknown";

  return [
    `# ${artifact.title}`,
    "",
    `**Employee:** ${artifact.employeeName}`,
    `**Team:** ${team}`,
    `**Owner:** ${artifact.owner}`,
    `**Risk Score:** ${riskScore} (${riskBucket})`,
    "",
    "---",
    "",
    "## Employee Context",
    "",
    `${artifact.employeeName} is showing ${riskBucket.toLowerCase()} burnout risk signals.`,
    rationale,
    "",
    "## Decision Rationale",
    "",
    rationale,
    "",
    "## Action Items",
    "",
    "- [ ] Review the employee's current meeting load and identify compressible sessions.",
    "- [ ] Coordinate with the employee on protected focus-block windows.",
    "- [ ] Monitor adoption of recommended changes over the next review cycle.",
    `- [ ] Follow-up cadence: **${followUpCadence}**.`,
    "",
    "---",
    "",
    `*Generated by Mediary — ${new Date().toISOString().split("T")[0]}*`,
    "",
  ].join("\n");
}

// ── Employee nudge ───────────────────────────────────────────────────────────

function formatEmployeeNudge(
  artifact: ActionArtifact,
  queueItem: InterventionQueueItem | undefined,
): string {
  const riskScore = queueItem?.riskScore ?? "N/A";
  const riskBucket = queueItem?.riskBucket ?? "N/A";
  const nextStep = queueItem?.nextStep ?? artifact.body;

  return [
    `# ${artifact.title}`,
    "",
    `**For:** ${artifact.employeeName}`,
    `**Risk Level:** ${riskBucket} (${riskScore})`,
    "",
    "---",
    "",
    "## What This Means",
    "",
    "Your recent calendar patterns suggest elevated workload strain.",
    "This is a heads-up, not a reprimand — small adjustments now can prevent bigger issues later.",
    "",
    "## Actionable Steps",
    "",
    `1. ${nextStep}`,
    "2. Block at least one 90-minute focus window this week.",
    "3. Review recurring meetings — flag any that could be async or shortened.",
    "4. Log how you feel at the end of each day for the next 5 working days.",
    "",
    "## Checkpoint",
    "",
    `**Date:** 7 days from delivery`,
    "",
    "---",
    "",
    `*Generated by Mediary — ${new Date().toISOString().split("T")[0]}*`,
    "",
  ].join("\n");
}

// ── Focus block plan ─────────────────────────────────────────────────────────

function formatFocusBlockPlan(
  artifact: ActionArtifact,
  queueItem: InterventionQueueItem | undefined,
): string {
  const riskScore = queueItem?.riskScore ?? "N/A";
  const riskBucket = queueItem?.riskBucket ?? "N/A";

  return [
    `# ${artifact.title}`,
    "",
    `**Employee:** ${artifact.employeeName}`,
    `**Owner:** ${artifact.owner}`,
    `**Risk Score:** ${riskScore} (${riskBucket})`,
    "",
    "---",
    "",
    "## Recommended Focus Blocks",
    "",
    "| Day | Window | Duration | Purpose |",
    "|-----|--------|----------|---------|",
    "| Tuesday | 09:00–10:30 | 90 min | Deep work — no meetings |",
    "| Thursday | 13:00–14:30 | 90 min | Deep work — no meetings |",
    "| Friday | 10:00–11:30 | 90 min | Planning & async catch-up |",
    "",
    "## Meeting Adjustments",
    "",
    "- Compress back-to-back meetings into contiguous blocks to create breathing room.",
    "- Move any after-hours meetings to core hours (09:00–17:00).",
    "- Convert status-update meetings to async written updates where possible.",
    "- Ensure at least a 15-minute buffer between consecutive meetings.",
    "",
    "---",
    "",
    `*Generated by Mediary — ${new Date().toISOString().split("T")[0]}*`,
    "",
  ].join("\n");
}

// ── HR Memo ──────────────────────────────────────────────────────────────────

function formatHrMemo(hrMemo: string): string {
  return [
    "# HR Operations Memo",
    "",
    `**Date:** ${new Date().toISOString().split("T")[0]}`,
    `**Subject:** Org-Wide Workload & Burnout Risk Assessment`,
    "",
    "---",
    "",
    hrMemo,
    "",
    "---",
    "",
    `*Generated by Mediary — ${new Date().toISOString().split("T")[0]}*`,
    "",
  ].join("\n");
}

// ── Follow-up checklist ──────────────────────────────────────────────────────

function formatFollowUpChecklist(tasks: FollowUpTask[]): string {
  const lines = [
    "# Follow-Up Task Checklist",
    "",
    `**Generated:** ${new Date().toISOString().split("T")[0]}`,
    "",
    "---",
    "",
  ];

  for (const task of tasks) {
    lines.push(`## ${task.employeeName} — ${task.owner}`);
    lines.push("");
    lines.push(`- **Due:** ${task.dueIn}`);
    lines.push(`- **Trigger:** ${task.trigger}`);
    lines.push(`- [ ] ${task.task}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(`*Generated by Mediary — ${new Date().toISOString().split("T")[0]}*`);
  lines.push("");

  return lines.join("\n");
}

// ── Main export ──────────────────────────────────────────────────────────────

/**
 * Write all deliverable files from a completed Mediary loop run.
 *
 * Creates the output directory if it doesn't exist. Each action artifact
 * gets its own `.md` file, plus a standalone HR memo and a follow-up
 * checklist file.
 */
export function writeDeliverables(
  output: Pick<
    MediaryLoopOutput,
    "actionArtifacts" | "followUpTasks" | "hrMemo" | "interventionQueue"
  >,
  outputDir: string = DEFAULT_OUTPUT_DIR,
): string[] {
  ensureDir(outputDir);

  const writtenPaths: string[] = [];
  const queue = output.interventionQueue ?? [];

  // ── Action artifacts ──
  for (const artifact of output.actionArtifacts) {
    const queueItem = findQueueItem(queue, artifact.employeeId);
    let content: string;
    let prefix: string;

    switch (artifact.type) {
      case "hr_ops_case":
        content = formatHrOpsCase(artifact, queueItem);
        prefix = "hr-ops-case";
        break;
      case "manager_brief":
        content = formatManagerBrief(artifact, queueItem);
        prefix = "manager-brief";
        break;
      case "employee_nudge":
        content = formatEmployeeNudge(artifact, queueItem);
        prefix = "employee-nudge";
        break;
      case "focus_block_plan":
        content = formatFocusBlockPlan(artifact, queueItem);
        prefix = "focus-block-plan";
        break;
      default:
        content = `# ${artifact.title}\n\n${artifact.body}\n`;
        prefix = artifact.type;
    }

    const filename = `${sanitizeFilename(prefix)}-${sanitizeFilename(artifact.employeeName)}.md`;
    const filePath = path.join(outputDir, filename);
    fs.writeFileSync(filePath, content, "utf-8");
    writtenPaths.push(filePath);
  }

  // ── HR Memo ──
  if (output.hrMemo) {
    const memoPath = path.join(outputDir, "hr-memo.md");
    fs.writeFileSync(memoPath, formatHrMemo(output.hrMemo), "utf-8");
    writtenPaths.push(memoPath);
  }

  // ── Follow-up checklist ──
  if (output.followUpTasks && output.followUpTasks.length > 0) {
    const checklistPath = path.join(outputDir, "follow-up-checklist.md");
    fs.writeFileSync(
      checklistPath,
      formatFollowUpChecklist(output.followUpTasks),
      "utf-8",
    );
    writtenPaths.push(checklistPath);
  }

  return writtenPaths;
}
